#server:
#  port: 0
#spring:
#  application:
#    name: eureka-client-2
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: eureka-client-2
  config:
    import: configserver:http://localhost:8888
  profiles:
    active: micro