server:
  port: 8888
spring:
  application:
    name: github-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AlexanderIab/planner-backend-micro-properties.git
          basedir: file://C:/git-prop-planner-micro
          clone-on-start: true
          username: AlexanderIab
          password: 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
          default-label: main